# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://qinjisheng.top
date_format: "ordinal"
title: 秦大圣的博客
subtitle: "公众号：计算机初学者"
description: "秦大圣的博客，公众号：计算机初学者"
keywords: 秦大圣，秦大圣的博客，计算机初学者
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5
repository: qinjisheng2018/qinjisheng2018.github.io
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: true
# 组件配置
components:
    # 分享
    share:
        enabled: false
    # 不蒜子访问统计
    busuanzi:
        enabled: true
        start_date: 2020-07-01
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 文章字数统计
word_count:
    enabled: true
# 代码高亮风格
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: Jisheng Qin
organization: 
organization_url: 
github_username: qinjisheng2018
location: Anhui, China
email: qinjisheng2018@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 博客首页

  -
    href: /wiki/
    label: 科研学习

  -
    href: /categories/
    label: 分类汇总

  -
    href: /links/
    label: 友情链接

   -
     href: /archives/
     label: 归档

   -
     href: /open-source/
     label: 开源

  -
    href: /about/
    label: 个人简介

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: qinjisheng
    repo: blog-comments
    oauth:
        client_id: 1b9ce312b6b247abd173
        client_secret: 89a4935d12cc530864641313a4caebe0845270cb
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: qinjisheng
    repo: blog-comments
    clientID: 1b9ce312b6b247abd173
    clientSecret: 89a4935d12cc530864641313a4caebe0845270cb
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: UA-80669434-1
    adsense:
        footer: true
        sidebar: true 
        content_header: true
        content_footer: false
